
#!/usr/bin/perl -w
use strict;

# parse the PSL file generated by BLAT 
# Author: Ying Zhang; yzhang@bccrc.ca
# Date: Nov 17, 2014

my $dataset = "c3h.input";
my $psl_file = "../results/blat/$dataset.flankmap.psl";

open (PSLFILE, "$psl_file") or die "cannot open psl file: $!";

my $output_file = "../results/blat/$dataset.locus.txt";
open (OUTFILE, ">$output_file") or die "cannot open OUTPUT file: $!";

for (my $i=0; $i<5; $i++) {
    <PSLFILE>;
}

while (<PSLFILE>) {
    chomp;
    my @fields = split /\t/;
    my $match = $fields[0];
    my $mismatch = $fields[1];
    my $read_id = $fields[9];
    my $uniseq_size = $fields[10];
    my $chr = $fields[13];
    my $start = $fields[15];
    my $end = $fields[16];
    
    my $percent = $match / $uniseq_size * 100;
    
    print OUTFILE "$read_id\t$percent\t$chr\t$start\t$end\n";
}

print "Done!\n";
